//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginatingDatatablesMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int IdEmpleado { get; set; }
        public string Documento { get; set; }
        public Nullable<System.DateTime> FechaEmisionDocumento { get; set; }
        public Nullable<System.DateTime> FechaVencimientoDocumento { get; set; }
        public int IdTipoDocumento { get; set; }
        public string Nombre { get; set; }
        public string SegundoNombre { get; set; }
        public string Apellido { get; set; }
        public string SegundoApellido { get; set; }
        public string NombreCompleto { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public Nullable<bool> Sexo { get; set; }
        public int IdEstadoCivil { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int Nacionalidad { get; set; }
        public int PaisNacimiento { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public Nullable<int> IdFoto { get; set; }
        public Nullable<int> IdNivelAcademico { get; set; }
        public Nullable<int> IdConyugue { get; set; }
        public Nullable<int> IdContactoEmergencia { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaEgreso { get; set; }
        public System.DateTime FechaPrimerIngreso { get; set; }
        public bool RequiereMarcar { get; set; }
        public bool GanaExtras { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public bool EstadoActivo { get; set; }
    }
}
